# Generated by Django 4.0.3 on 2022-03-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
    ]
