# Generated by Django 4.0.3 on 2022-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
