# Generated by Django 4.0.3 on 2022-03-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
