# Generated by Django 4.0.3 on 2022-03-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_task_info_task_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_date',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
    ]
